config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :custom_trips, only: [:create, :new]

  mount Crono::Web, at: '/crono'
  get 'messages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tours, except: [:edit, :update] do
    resources :tour_details, only: [:create, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
    resources :tour_reviews, only: [:create, :destroy]
  end

  resources :blogs
  resources :locations
  get '/card/new' => 'bookings#new_card', as: :add_payment_method
  post "/card" => "bookings#create_card", as: :create_payment_method
  get '/success' => 'bookings#success', as: :success

  resources :hotels do
    resources :hotel_rooms, except: [:index]
    resources :hotel_reviews, only: [:create, :destroy]
  end
  resources :car_rentals do
    resources :vehicles
  end
  resources :car_rental_owners do
    get :my_car_rentals
  end
  resources :trip_organizers do
    get :my_tours
  end
  resources :hotel_managers do
    get :my_hotels
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end



  get 'charges/:id', to: 'charges#new', as: :new_charge
  post 'charges/:id', to: 'charges#create', as: :charges

  get 'featured_charges/:id', to: 'featured_charges#new', as: :new_featured_charge
  post 'featured_charges/:id', to: 'featured_charges#create', as: :featured_create

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :contact, only: [:index]
  resources :about, only: [:index]
  resources :posts do
    post 'delete_image_attachment/:id', to: 'posts#delete_image_attachment', as: :delete_image_attachment
  end

  resources :comments, only: [:create, :destroy]
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end
  get '/my_bookings/:id', to: 'users#my_bookings', as: :my_bookings
  resources :events, except: [:edit, :update]


    get '/feed', to:  'feed#index'

    get '/feed/front', as: "home"


  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'feed#find_friends', as: :find_friends, via: :get
  match :about, to: 'feed#about', as: :about, via: :get




  namespace :api do
    resources :tours, only: [:index, :create, :update, :destroy, :show]

    resource :users, only: [:show]
    resource :trip_organizers, only: [:create, :show, :destroy, :update, :index]
    resource :tour_details, only: [:update, :show, :destroy]
    resource :bookings, only: [:create, :destroy, :show]
      devise_for :users, as: 'api', controllers: {
          session: 'api/sessions', registrations: 'api/users/registrations'}, skip: [:password]
  end


  namespace :dashboard do
    resources :trip_organizers, only: [:index, :update]
    resources :tours, only: [:destroy, :create, :edit ,:update] do
      resources :tour_details, only: [:index, :update]
      resources :featured_tours
    end

    resources :hotel_managers, only: [:update, :index]
    resources :hotels, only: [:destroy, :create, :update, :edit] do
      resources :hotel_rooms, only: [:index, :update, :create, :new, :index]
      resources :featured_hotels, only: [:new, :create]
    end

    resources :car_rental_owners, only: [:update, :index]
    resources :car_rentals, only: [:destroy, :create, :update, :edit] do
      resources :vehicles, only: [:index, :update, :create, :new, :index]
    end
  end
end

app/models/hotel_room.rb
class HotelRoom < ApplicationRecord
  belongs_to :hotel , foreign_key: 'hotels_id'
  has_many_attached :hotel_room_pictures

  validates :price, numericality: true
  validates :number_of_beds, numericality: true
  validates :room_type, presence: true
  validates :hotel_room_pictures, presence: true
end

app/controllers/dashboard/hotel_rooms_controller.rb
class Dashboard::HotelRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_hotel_manager?
  before_action :set_hotel_room, only: [:update, :destroy]
  before_action :set_hotel
  before_action :set_hotel_room_facilities_names, only: [:new, :create, :update, :index]
  before_action :set_keys, only: [:new, :create, :update, :index]
  after_action :update_hotel_rate, only: [:update, :create, :destroy]
  # GET /hotel_rooms/new


  def new
      @hotel_room = HotelRoom.new
  end

  def index
    @hotel_rooms = @hotel.hotel_rooms
  end


  # POST /hotel_rooms
  # POST /hotel_rooms.json
  def create
    @hotel_room = HotelRoom.new(hotel_room_params)
    @hotel_room.hotels_id = params[:hotel_id]
    facilitites_params = params[:facilities]
    if facilitites_params.include?(1.to_s)
      @hotel_room.heater = true
    end
    if facilitites_params.include?(2.to_s)
      @hotel_room.air_conditioned = true
    end
    if facilitites_params.include?(3.to_s)
      @hotel_room.tv = true
    end
    if facilitites_params.include?(4.to_s)
      @hotel_room.kitchenette = true
    end
    if facilitites_params.include?(5.to_s)
      @hotel_room.refrigerator = true
    end
    if facilitites_params.include?(6.to_s)
      @hotel_room.microwave = true
    end
    respond_to do |format|
      if @hotel_room.save
        format.js
        format.html { redirect_to hotel_hotel_room_path(@hotel,@hotel_room) }
      else
        render :'dashboard/hotel_rooms/create_failed.js'
      end
    end
  end

  # PATCH/PUT /hotel_rooms/1
  # PATCH/PUT /hotel_rooms/1.json
  def update
      facilitites_params = params[:facilities]
      if facilitites_params.include?(1.to_s)
        @hotel_room.heater = true
      else
        @hotel_room.heater = false
      end
      if facilitites_params.include?(2.to_s)
        @hotel_room.air_conditioned = true
      else
        @hotel_room.air_conditioned = false
      end
      if facilitites_params.include?(3.to_s)
        @hotel_room.tv = true
      else
        @hotel_room.tv = false
      end
      if facilitites_params.include?(4.to_s)
        @hotel_room.kitchenette = true
      else
        @hotel_room.kitchenette = false
      end
      if facilitites_params.include?(5.to_s)
        @hotel_room.refrigerator = true
      else
        @hotel_room.refrigerator = false
      end
      if facilitites_params.include?(6.to_s)
        @hotel_room.microwave = true
      else
        @hotel_room.microwave = false
      end
      respond_to do |format|
        if @hotel_room.update(hotel_room_params)
          format.html { redirect_to hotel_hotel_room_path(@hotel,@hotel_room)}
        else
          format.js { render  :'dashboard/hotel_rooms/update_failed'}
        end
      end
  end

  # DELETE /hotel_rooms/1
  # DELETE /hotel_rooms/1.json
  def destroy
    @hotel_room.destroy
    respond_to do |format|
      format.html { redirect_to @hotel, notice: 'Hotel room was successfully destroyed, at night ;).' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    def is_hotel_manager?
      redirect_to root_path unless current_user.is_hotel_manager == true
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_room
      @hotel_room = HotelRoom.find(params[:id])
    end

    def set_hotel
      @hotel = Hotel.eager_load(:hotel_rooms, :hotel_reviews).find(params[:hotel_id])
    end

    def set_hotel_room_facilities_names
      @hotel_room_facilities_name = HotelRoomFacility.all
    end

    def set_keys
      dummy_hotel_room = HotelRoom.new
      @keys = dummy_hotel_room.attribute_names
    end

    def update_hotel_rate
      @hotel.update(rate: @hotel.hotel_rooms.minimum("price").to_s + " - " +  @hotel.hotel_rooms.maximum("price").to_s)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_room_params
      params.require(:hotel_room).permit(:room_type, :price, :number_of_beds ,facilities:[], hotel_room_pictures:[])
    end
end

app/controllers/hotel_rooms_controller.rb
class HotelRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hotel_room, only: [:show, :edit, :update, :destroy, :show]
  before_action :set_hotel
  before_action :set_hotel_room_facilities_names, only: [:new, :edit, :create, :update, :show]
  before_action :set_keys, only: [:new, :edit, :create, :update, :show]
  after_action :update_hotel_rate, only: [:update, :create, :destroy]
  # GET /hotel_rooms/new
  respond_to  :js

  def show
    @hotel_review  = HotelReview.new
    @hotel_reviews = @hotel.hotel_reviews.eager_load(:user).paginate(:per_page => 5, :page => params[:page]).order('hotel_reviews.created_at DESC')
  end

  def new
    @user = User.find current_user.id
    if(!@user.hotel_manager.nil?)
      @hotel_room = HotelRoom.new
    else
      redirect_to root_path
    end
  end

  # GET /hotel_rooms/1/edit
  def edit
    @user = User.find current_user.id
    if(@user.hotel_manager.nil?)
      redirect_to root_path
    end
  end

  # POST /hotel_rooms
  # POST /hotel_rooms.json
  def create
    @hotel_room = HotelRoom.new(hotel_room_params)
    @hotel_room.hotels_id = params[:hotel_id]
    facilitites_params = params[:facilities]
    if facilitites_params.include?(1.to_s)
      @hotel_room.heater = true
    end
    if facilitites_params.include?(2.to_s)
      @hotel_room.air_conditioned = true
    end
    if facilitites_params.include?(3.to_s)
      @hotel_room.tv = true
    end
    if facilitites_params.include?(4.to_s)
      @hotel_room.kitchenette = true
    end
    if facilitites_params.include?(5.to_s)
      @hotel_room.refrigerator = true
    end
    if facilitites_params.include?(6.to_s)
      @hotel_room.microwave = true
    end
    respond_to do |format|
      if @hotel_room.save
        format.html { redirect_to @hotel, notice: '6969 Hotel room was successfully created. Have fun! 6969' }
        format.json { render :show, status: :created, location: @hotel_room }
      else
        format.html { render :new }
        format.json { render json: @hotel_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotel_rooms/1
  # PATCH/PUT /hotel_rooms/1.json
  def update
    @user = User.find current_user.id
    if(!@user.hotel_manager.nil?)
      facilitites_params = params[:facilities]
      if facilitites_params.include?(1.to_s)
        @hotel_room.heater = true
      else
        @hotel_room.heater = false
      end
      if facilitites_params.include?(2.to_s)
        @hotel_room.air_conditioned = true
      else
        @hotel_room.air_conditioned = false
      end
      if facilitites_params.include?(3.to_s)
        @hotel_room.tv = true
      else
        @hotel_room.tv = false
      end
      if facilitites_params.include?(4.to_s)
        @hotel_room.kitchenette = true
      else
        @hotel_room.kitchenette = false
      end
      if facilitites_params.include?(5.to_s)
        @hotel_room.refrigerator = true
      else
        @hotel_room.refrigerator = false
      end
      if facilitites_params.include?(6.to_s)
        @hotel_room.microwave = true
      else
        @hotel_room.microwave = false
      end
      respond_to do |format|
        if @hotel_room.update(hotel_room_params)
          format.html { redirect_to @hotel, notice: '6969 Hotel room was successfully created. Have fun! 6969' }
          format.json { render :show, status: :created, location: @hotel_room }
        else
          format.html { render :new }
          format.json { render json: @hotel_room.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /hotel_rooms/1
  # DELETE /hotel_rooms/1.json
  def destroy
    @hotel_room.destroy
    respond_to do |format|
      format.html { redirect_to @hotel, notice: 'Hotel room was successfully destroyed, at night ;).' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_room
      @hotel_room = HotelRoom.find(params[:id])
    end

    def set_hotel
      @hotel = Hotel.eager_load(:hotel_rooms, :hotel_reviews, :hotel_manager).find(params[:hotel_id])
    end

    def set_hotel_room_facilities_names
      @hotel_room_facilities_name = HotelRoomFacility.all
    end

    def set_keys
      dummy_hotel_room = HotelRoom.new
      @keys = dummy_hotel_room.attribute_names
    end

    def update_hotel_rate
      @hotel.update(rate: @hotel.hotel_rooms.minimum("price").to_s + " - " +  @hotel.hotel_rooms.maximum("price").to_s)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_room_params
      params.require(:hotel_room).permit(:room_type, :price, :number_of_beds ,facilities:[], hotel_room_pictures:[])
    end
end

app/helpers/hotel_rooms_helper.rb
module HotelRoomsHelper
end

app/views/hotel_rooms/_excludedfacilities.html.erb
<% @hotel_room_facilities_name.each do |facility| %>
  <% if @hotel_room[@keys[(facility.id)+2]] == false %>
    <li><i class="fa fa-times" aria-hidden="true"></i><%= facility.name %></li>
  <% end %>
<% end %>

app/views/hotel_rooms/_form.html.erb
<%= form_with(model: [@hotel,@hotel_room], local: true) do |form| %>
<!--  <div class="wrapper-content">-->
<!--    < HEADER-->
<!--    <header></header>-->
<!--    < WRAPPER-->
<!--    <div id="wrapper-content">-->
<!--      <! MAIN CONTENT-->-->
<!--      <div class="main-content">-->
<!--        <section class="page-login">-->
<!--          <div class="container wrapper-login">-->
<!--            <div class="content-login">-->
<!--              <div class="main-login">-->
<!--                <div class="logo-login">-->
<!--                  <a href="index.html" class="logo-black">-->
<!--                    <img src="assets/images/logo/logo-black-color-1.png" alt="" class="img img-reponsive">-->
<!--                  </a>-->
<!--                </div>-->
                <%# if hotel_room.errors.any? %>
<!--                  <div id="error_explanation">-->
<!--                    <h2><%#= pluralize(hotel_room.errors.count, "error") %> prohibited this hotel_room from being saved:</h2>-->
<!--                    <ul>-->
                      <%# hotel_room.errors.full_messages.each do |message| %>
<!--                        <li><%#= message %></li>-->
                      <%# end %>
<!--                    </ul>-->
<!--                  </div>-->
                <%# end %>
<!--                <div class="login-title">Add a New Hotel Room Type !</div>-->
<!--                <div class="login-form">-->
<!--                  <div class="row">-->
<!--                    <div class="content-form">-->
<!--                      <div class="col-md-6">-->
<!--                        <div class="form-login">-->
<!--                          <div class="input-login">-->
                            <%#= form.label :room_type, class:"label-login" %>
<!--                            <br>-->
                            <%#= form.select :room_type, options_for_select([["Select One", "Simple"], "Single Room", "Double Room", "Triple Room", "Quad Room", "Twin Room","Luxury Room","Studio","Mini Suite","Master Suite","Hut","Cottage"], selected: @hotel_room.room_type || nil ), {},:class => 'form-control label-input' %>
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                      <div class="col-md-6">-->
<!--                        <div class="form-login">-->
<!--                          <div class="input-login">-->
                            <%#= form.label :price, class:"label-login" %>
                            <%#= form.number_field :price, class:"form-control label-input" %>
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                      <div class="col-md-6">-->
<!--                        <div class="form-login">-->
<!--                          <div class="input-login">-->
                            <%#= form.label :number_of_beds, class:"label-login" %>
                            <%#= form.number_field :number_of_beds, class:"form-control label-input" %>
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                      <div class="col-md-6">-->
<!--                        <div class="form-login">-->
<!--                          <div class="input-login">-->
                            <%#= form.label :hotel_room_pictures, class:"label-login"  %>
                            <%#= form.file_field :hotel_room_pictures, class:"form-control", multiple:"true" %>
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                      <div class="col-md-6">-->
<!--                        <div class="form-login">-->
<!--                          <div class="input-login">-->
<!--                            <label for="hotel_facility_name_id">Room Facilities</label>-->
<!--                            <br>-->
                            <%# if @keys.empty? %>
                              <%# @hotel_room_facilities_name.each do |facility| %>
                                <%#= check_box_tag("facilities[]" , facility.id) %>
                                <%#= facility.name %>
<!--                                <br>-->
                              <%# end %>
                            <%# else %>
                              <%# @hotel_room_facilities_name.each do |facility| %>
                                <%# if @hotel_room[@keys[(facility.id)+2]] %>
                                  <%#= check_box_tag("facilities[]" , facility.id , checked: true) %>
                                <%# else %>
                                  <%#= check_box_tag("facilities[]" , facility.id) %>
                                <%# end %>
                                <%#= facility.name %>
<!--                                <br>-->
                              <%# end %>
                            <%# end %>
<!--                          </div>-->
<!--                        </div>-->
<!--                      </div>-->
<!--                      <div class="clearfix"></div>-->
<!--                      <div class="contact-submit">-->
<!--                        <button type="submit" data-hover="Add Now" class="btn-slide">-->
<!--                          <span class="text">Add Hotel </span>-->
<!--                          <span class="icons fa fa-long-arrow-right"></span>-->
<!--                        </button>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
                <%#= link_to 'Back', hotels_path %>
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </section>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<%# end %>
  <!-- Breadcrumb -->
  <section class="breadcrumb-outer text-center">
    <div class="container">
      <div class="breadcrumb-content">
        <h2>Add A New Hotel</h2>
        <nav aria-label="breadcrumb">
        </nav>
      </div>
    </div>
    <div class="section-overlay"></div>
  </section>
  <!-- BreadCrumb Ends -->

  <section class="booking">
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="booking-form booking-outer">
            <%= form_for([:dashboard, hotel], local: true, class: "custom-form", remote: true, authenticity_token: true) do |form| %>
              <div id="error_explanation">
                <% if hotel.errors.any? %>
                  <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>
                  <ul>
                    <% hotel.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
              <div class="row">
                <div class="form-group col-xs-6">
                  <%= form.label :name, style: 'text-transform: capitalize',class:"label-login" %>
                  <%= form.text_field :name,placeholder:"Hotel Name", style: 'text-transform: capitalize', class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <%= form.label :number, style: 'text-transform: capitalize; ',class:"label-login" %>
                  <%= form.number_field :number,placeholder:"Hotel Contact Number", style: 'text-transform: capitalize; ', class:"form-control" %>
                </div>
                <div class="form-group col-xs-6 ">
                  <%= form.label :email, style: 'text-transform: capitalize; ',class:"label-login" %>
                  <%= form.email_field :email,placeholder:"Hotel Email", class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <%= form.label :address, style: 'text-transform: capitalize; ',class:"label-login" %>
                  <%= form.text_field :address,placeholder:"Hotel Address", style: 'text-transform: capitalize;', class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <%= form.label :website_url, style: 'text-transform: capitalize; ',class:"label-login" %>
                  <%= form.text_field :website_url,placeholder:"Website URL (Optional)", class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <label>Location</label>
                  <%=  form.collection_select(:locations_id, Location.all, :id, :name, prompt: true, class:"form-control required", required:"true" )%>
                </div>
                <div class="textarea col-xs-12">
                  <%= form.label :info,style: 'text-transform: capitalize;' , class:"label-login"  %>
                  <%= form.cktext_area :info, class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <%= form.label :proof_of_ownership,  style: 'text-transform: capitalize;',class:"label-login"  %>
                  <%= form.file_field :proof_of_ownership, class:"form-control" %>
                </div>
                <div class="form-group col-xs-6">
                  <%= form.label :hotel_cover_photos,style: 'text-transform: capitalize;', class:"label-login"  %>
                  <%= form.file_field :hotel_cover_photos, class:"form-control", multiple:"true" %>
                </div>

                <label class="label-login">Hotel Facilities</label>
                <div class="form-control col-xs-12">
                  <ul class="checkbox-grid">
                    <% if @keys.nil? || @keys.empty? %>
                      <% @hotel_facilities_name.each do |facility| %>
                        <li>
                          <label class="checkbox-inline">
                            <%= check_box_tag("facilities[]" , facility.id) %>
                            <%= facility.name %>
                          </label>
                        </li>
                      <% end %>
                    <% else %>
                      <% @hotel_facilities_name.each do |facility| %>
                        <li>
                          <label class="checkbox-inline">
                            <% if @hotel_facilities[@keys[(facility.id)+1]] %>
                              <%= check_box_tag("facilities[]" , facility.id , checked: true) %>
                            <% else %>
                              <%= check_box_tag("facilities[]" , facility.id) %>
                            <% end %>
                            <%= facility.name %>
                          </label>
                        </li>
                      <% end %>
                    <% end %>
                  </ul>
                </div>

                <div class="col-xs-12">
                  <div class="comment-btn">
                    <%= form.submit "Add Hotel", class: "btn-blue btn-red" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

<% end %>

app/views/hotel_rooms/_hotel_room.html.erb
<div class="col-sm-4" id="hotel-room-<%#= hotel_room.id %>">
  <div class="package-item">
    <a href="<%= hotel_hotel_room_path(hotel_room.hotel,hotel_room) %>">
      <div class="hotel-room-thumbnail">
        <%= image_tag hotel_room.hotel_room_pictures[0],class: "hotel-cover-photo-thumbnail", alt:'Hotel Room' %>
      </div>
      <div class="package-content">
        <h5>Starting: <span>$<%= hotel_room.price %></span> / PER </h5>
        <h3><a href="#"><%= hotel_room.room_type %></a></h3>
      </div>
    </a>
  </div>
</div>

app/views/hotel_rooms/_includedfacilities.html.erb
<% @hotel_room_facilities_name.each do |facility| %>
  <% if @hotel_room[@keys[(facility.id)+2]] %>
    <li><i class="fa fa-check" aria-hidden="true"></i><%= facility.name %></li>
  <% end %>
<% end %>

app/views/hotel_rooms/_relatedrooms.html.erb
<% hotel.hotel_rooms.each do |hotel_room| %>
  <% if hotel_room != current_room %>
    <div class="sidebar-package">
      <div class="sidebar-package-image">
        <img src="<%= rails_blob_url(hotel_room.hotel_room_pictures[0]) %>" alt="Images">
      </div>
      <div class="destination-content sidebar-package-content">
        <h4><a href="hotel-detail.html"><%= hotel_room.room_type %></a></h4>
        <p><i class="flaticon-time"></i> Starting from <span class="bold">Pkr<%= hotel_room.price %></span> </p>
        <a href="<%= hotel_hotel_room_path(hotel,hotel_room) %>" class=" btn-red">See More</a>
      </div>
    </div>
  <% end %>
<% end %>

app/views/hotel_rooms/_roomgallery.html.erb
<!-- Indicators -->
<ol class="carousel-indicators">
  <!-- 1st Indicator -->
  <% room_pictures.each_with_index do |img,index| %>
    <% if img == room_pictures[0]%>
      <li data-target="#in_th_030" data-slide-to="<%= index %>" class="active">
    <% else %>
      <li data-target="#in_th_030" data-slide-to="<%= index %>">
    <% end %>
    <img src="<%= rails_blob_url(img) %>" alt="room_picture" />
    </li>
  <% end %>
</ol> <!-- /Indicators -->
<!-- Wrapper For Slides -->
<div class="carousel-inner" role="listbox">
  <% room_pictures.each do |img| %>
    <% if img == room_pictures[0]%>
      <div class="item active">
    <% else %>
      <div class="item">
    <% end %>
    <img src="<%= rails_blob_url(img) %>" alt="room_picture" />
    </div>
  <% end %>
</div> <!-- End of Wrapper For Slides -->

app/views/hotel_rooms/destroy.js.erb
$('.delete-hotel-room').bind('ajax:success', function() {
    $('div[id^="hotel-room-"]').fadeOut();
});

app/views/hotel_rooms/edit.html.erb
<%= render 'form', hotel_room: @hotel_room %>

<%= link_to 'Back', hotels_path %>

app/views/hotel_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotel Rooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotel_rooms.each do |hotel_room| %>
      <tr>
        <td><%= link_to 'Show', hotel_room %></td>
        <td><%= link_to 'Edit', edit_hotel_room_path(hotel_room) %></td>
        <td><%= link_to 'Destroy', hotel_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel Room', new_hotel_room_path %>

app/views/hotel_rooms/new.html.erb
<%= render 'form', hotel_room: @hotel_room %>

app/views/hotel_rooms/show.js.erb
$('div[id^="hotel-review-"]').remove();
<%= @hotel_reviews.each do |review| %>
$("#review_box").html("<%= escape_javascript(render  "hotel_reviews/hotel_review", review: review) %>");
<% end %>
$("#hotel_review_paginate").html("<%= j js_will_paginate @hotel_reviews %>");