config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :custom_trips, only: [:create, :new]

  mount Crono::Web, at: '/crono'
  get 'messages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tours, except: [:edit, :update] do
    resources :tour_details, only: [:create, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
    resources :tour_reviews, only: [:create, :destroy]
  end

  resources :blogs
  resources :locations
  get '/card/new' => 'bookings#new_card', as: :add_payment_method
  post "/card" => "bookings#create_card", as: :create_payment_method
  get '/success' => 'bookings#success', as: :success

  resources :hotels do
    resources :hotel_rooms, except: [:index]
    resources :hotel_reviews, only: [:create, :destroy]
  end
  resources :car_rentals do
    resources :vehicles
  end
  resources :car_rental_owners do
    get :my_car_rentals
  end
  resources :trip_organizers do
    get :my_tours
  end
  resources :hotel_managers do
    get :my_hotels
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end



  get 'charges/:id', to: 'charges#new', as: :new_charge
  post 'charges/:id', to: 'charges#create', as: :charges

  get 'featured_charges/:id', to: 'featured_charges#new', as: :new_featured_charge
  post 'featured_charges/:id', to: 'featured_charges#create', as: :featured_create

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :contact, only: [:index]
  resources :about, only: [:index]
  resources :posts do
    post 'delete_image_attachment/:id', to: 'posts#delete_image_attachment', as: :delete_image_attachment
  end

  resources :comments, only: [:create, :destroy]
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end
  get '/my_bookings/:id', to: 'users#my_bookings', as: :my_bookings
  resources :events, except: [:edit, :update]


    get '/feed', to:  'feed#index'

    get '/feed/front', as: "home"


  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'feed#find_friends', as: :find_friends, via: :get
  match :about, to: 'feed#about', as: :about, via: :get




  namespace :api do
    resources :tours, only: [:index, :create, :update, :destroy, :show]

    resource :users, only: [:show]
    resource :trip_organizers, only: [:create, :show, :destroy, :update, :index]
    resource :tour_details, only: [:update, :show, :destroy]
    resource :bookings, only: [:create, :destroy, :show]
      devise_for :users, as: 'api', controllers: {
          session: 'api/sessions', registrations: 'api/users/registrations'}, skip: [:password]
  end


  namespace :dashboard do
    resources :trip_organizers, only: [:index, :update]
    resources :tours, only: [:destroy, :create, :edit ,:update] do
      resources :tour_details, only: [:index, :update]
      resources :featured_tours
    end

    resources :hotel_managers, only: [:update, :index]
    resources :hotels, only: [:destroy, :create, :update, :edit] do
      resources :hotel_rooms, only: [:index, :update, :create, :new, :index]
      resources :featured_hotels, only: [:new, :create]
    end

    resources :car_rental_owners, only: [:update, :index]
    resources :car_rentals, only: [:destroy, :create, :update, :edit] do
      resources :vehicles, only: [:index, :update, :create, :new, :index]
    end
  end
end

app/controllers/tour_reviews_controller.rb
class TourReviewsController < ApplicationController
  before_action :set_tour_review, only: [:update, :destroy]
  # POST /tour_reviews
  # POST /tour_reviews.json
  def create
    @tour_review = TourReview.new(tour_review_params)
    @tour_review.tour_id = params[:tour_id]
    @tour_review.user_id = current_user.id
    respond_to do |format|
      if @tour_review.save
        format.js
      end
    end
  end

  # PATCH/PUT /tour_reviews/1
  # PATCH/PUT /tour_reviews/1.json
  def update
    respond_to do |format|
      if @tour_review.update(tour_review_params)
        format.html { redirect_to @tour_review, notice: 'Tour review was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour_review }
      else
        format.html { render :edit }
        format.json { render json: @tour_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_reviews/1
  # DELETE /tour_reviews/1.json
  def destroy
    @tour_review.destroy
    respond_to do |format|
      format.html { redirect_to tour_reviews_url, notice: 'Tour review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_review
      @tour_review = TourReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_review_params
      params.require(:tour_review).permit(:review_text, :rating)
    end
end

app/helpers/tour_reviews_helper.rb
module TourReviewsHelper
end

app/views/tour_reviews/_form.html.erb
<%= form_for([@tour, @tour_review],local: true, remote: true) do |form| %>
  <% if tour_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour_review.errors.count, "error") %> prohibited this tour_review from being saved:</h2>

      <ul>
        <% tour_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="textarea form-group col-xs-12">
<%= form.label :review_text, class:"label-login"  %>
<%= form.text_area :review_text, class:"form-control label-input" %>
</div>
<div class="form-group col-xs-12" style="display: none">
<%= form.label :rating, class:"label-login"  %>
<%= form.number_field :rating, class:"form-control label-input" %>
</div>
<div class="form-group col-xs-12">
  <div class='rating-widget'>

    <!-- Rating Stars Box -->
    <div class='rating-stars text-center'>
      <ul id='stars'>
        <li class='star' title='Poor' data-value='1'>
          <i class='fa fa-star fa-fw'></i>
        </li>
        <li class='star' title='Fair' data-value='2'>
          <i class='fa fa-star fa-fw'></i>
        </li>
        <li class='star' title='Good' data-value='3'>
          <i class='fa fa-star fa-fw'></i>
        </li>
        <li class='star' title='Excellent' data-value='4'>
          <i class='fa fa-star fa-fw'></i>
        </li>
        <li class='star' title='WOW!!!' data-value='5'>
          <i class='fa fa-star fa-fw'></i>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="col-xs-12">
<div class="comment-btn text-center">
  <%= form.submit class: "btn btn-red" %>
</div>
</div>
<% end %>

app/views/tour_reviews/_tour_review.html.erb
<div class="comment-item" id="tour-review-<%= review.id %>"><div class="row"><div class="col-md-4 col-sm-4"><div class="comment-image"><% if review.user.profile_picture.attached? %><img src="<%= url_for review.user.profile_picture %>" alt="Images"><% else %><img src="<%= image_path "user_default" %>" alt="Images"><% end %><h4><a href="<%= user_path review.user %>"><%= review.user.name %></a></h4><span class="comment-date"> <%= time_ago_in_words review.created_at %> </span></div></div><div class="col-md-8 col-sm-8 ml-3"><div class="comment-desc"><div class="deal-rating"><% review.rating.times do %><span class="fa fa-star checked"></span><% end %><% (5 - review.rating).times do %><span class="fa fa-star-o"></span><% end %></div><p><%= review.review_text %></p></div></div></div></div>

app/views/tour_reviews/create.js.erb
$('#review_box').prepend('<%= render "tour_reviews/tour_review", review: @tour_review %>');
document.getElementById("tour-review-<%= @tour_review.id %>").scrollIntoView();
$('#tour_review_review_text')[0].value = "";
$('#tour_review_rating')[0].value = "";
$('#stars > li').removeClass("selected");
$('.comments-form').remove();

app/views/tour_reviews/edit.html.erb
<h1>Editing Tour Review</h1>

<%= render 'form', tour_review: @tour_review %>

<%= link_to 'Show', @tour_review %> |
<%= link_to 'Back', tour_reviews_path %>

app/views/tour_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tour Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tour_reviews.each do |tour_review| %>
      <tr>
        <td><%= link_to 'Show', tour_review %></td>
        <td><%= link_to 'Edit', edit_tour_review_path(tour_review) %></td>
        <td><%= link_to 'Destroy', tour_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour Review', new_tour_review_path %>

app/views/tour_reviews/new.html.erb
<h1>New Tour Review</h1>

<%= render 'form', tour_review: @tour_review %>

<%= link_to 'Back', tour_reviews_path %>

app/views/tour_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tour_review_path(@tour_review) %> |
<%= link_to 'Back', tour_reviews_path %>