config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :custom_trips, only: [:create, :new]

  mount Crono::Web, at: '/crono'
  get 'messages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tours, except: [:edit, :update] do
    resources :tour_details, only: [:create, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
    resources :tour_reviews, only: [:create, :destroy]
  end

  resources :blogs
  resources :locations
  get '/card/new' => 'bookings#new_card', as: :add_payment_method
  post "/card" => "bookings#create_card", as: :create_payment_method
  get '/success' => 'bookings#success', as: :success

  resources :hotels do
    resources :hotel_rooms, except: [:index]
    resources :hotel_reviews, only: [:create, :destroy]
  end
  resources :car_rentals do
    resources :vehicles
  end
  resources :car_rental_owners do
    get :my_car_rentals
  end
  resources :trip_organizers do
    get :my_tours
  end
  resources :hotel_managers do
    get :my_hotels
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end



  get 'charges/:id', to: 'charges#new', as: :new_charge
  post 'charges/:id', to: 'charges#create', as: :charges

  get 'featured_charges/:id', to: 'featured_charges#new', as: :new_featured_charge
  post 'featured_charges/:id', to: 'featured_charges#create', as: :featured_create

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :contact, only: [:index]
  resources :about, only: [:index]
  resources :posts do
    post 'delete_image_attachment/:id', to: 'posts#delete_image_attachment', as: :delete_image_attachment
  end

  resources :comments, only: [:create, :destroy]
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end
  get '/my_bookings/:id', to: 'users#my_bookings', as: :my_bookings
  resources :events, except: [:edit, :update]


    get '/feed', to:  'feed#index'

    get '/feed/front', as: "home"


  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'feed#find_friends', as: :find_friends, via: :get
  match :about, to: 'feed#about', as: :about, via: :get




  namespace :api do
    resources :tours, only: [:index, :create, :update, :destroy, :show]

    resource :users, only: [:show]
    resource :trip_organizers, only: [:create, :show, :destroy, :update, :index]
    resource :tour_details, only: [:update, :show, :destroy]
    resource :bookings, only: [:create, :destroy, :show]
      devise_for :users, as: 'api', controllers: {
          session: 'api/sessions', registrations: 'api/users/registrations'}, skip: [:password]
  end


  namespace :dashboard do
    resources :trip_organizers, only: [:index, :update]
    resources :tours, only: [:destroy, :create, :edit ,:update] do
      resources :tour_details, only: [:index, :update]
      resources :featured_tours
    end

    resources :hotel_managers, only: [:update, :index]
    resources :hotels, only: [:destroy, :create, :update, :edit] do
      resources :hotel_rooms, only: [:index, :update, :create, :new, :index]
      resources :featured_hotels, only: [:new, :create]
    end

    resources :car_rental_owners, only: [:update, :index]
    resources :car_rentals, only: [:destroy, :create, :update, :edit] do
      resources :vehicles, only: [:index, :update, :create, :new, :index]
    end
  end
end

app/controllers/api/trip_organizers_controller.rb
class Api::TripOrganizersController < Api::ApplicationController
  before_action :authenticate_user_from_token!
  before_action :set_trip_organizer, only: [:show, :update, :destroy]
  # GET /trip_organizers
  # GET /trip_organizers.json
  def index
    @trip_organizers = TripOrganizer.all
  end

  # GET /trip_organizers/1
  # GET /trip_organizers/1.json
  def show
    render json: @trip_organizer
  end

  # POST /trip_organizers
  # POST /trip_organizers.json
  def create
    @trip_organizer = TripOrganizer.new(trip_organizer_params)
    @trip_organizer.user_id = @user.id
      if @trip_organizer.save
        @user.is_trip_organizer = true
        @user.save
        render json: @trip_organizer
      else
        render json: @trip_organizer.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /trip_organizers/1
  # PATCH/PUT /trip_organizers/1.json
  def update
      if @trip_organizer.update(trip_organizer_params)
        render json: @trip_organizer
      else
        render json: @trip_organizer.errors, status: :unprocessable_entity
      end
  end

  # DELETE /trip_organizers/1
  # DELETE /trip_organizers/1.json
  def destroy
    @trip_organizer.destroy
      format.json { head :no_content }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_organizer
      @trip_organizer = TripOrganizer.where(user_id: @user.id)[0]
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    def trip_organizer_params
      params.permit(:company_name, :about, :address, :license, :user_token, :email, :company_email, :company_number, :terms, :company_logo)
    end


  def authenticate_user_from_token!
    user_email = params[:email].presence
    user = user_email && User.find_by_email(user_email)

    # Notice how we use Devise.secure_compare to compare the token
    # in the database with the token given in the params, mitigating
    # timing attacks.
    if user && Devise.secure_compare(user.authentication_token, params[:user_token])
      @user = User.find_by_email(user_email)
      params.delete :user_token
      params.delete :email
      return true
    else
      render :json => '{"success" : "false"}'
    end
  end
end

app/controllers/dashboard/car_rental_owners_controller.rb
class Dashboard::CarRentalOwnersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_car_rental_owner?
  before_action :set_car_rental_owner, only: [:index, :update]

  def index
    @car_rental = CarRental.new
    @car_rentals = @car_rental_owner.car_rentals.order(created_at: :desc)
  end

  def update
    respond_to do |format|
      if @car_rental_owner.update(car_rental_owner_params)
        format.html { redirect_to @car_rental_owner, notice: 'Successfully updated.' }
        format.json { render :show, status: :ok, location: @car_rental_owner }
      else
        format.html { render :edit }
        format.json { render json: @car_rental_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def is_car_rental_owner?
    redirect_to root_path unless current_user.is_car_rental_owner == true
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_car_rental_owner
    @car_rental_owner = CarRentalOwner.eager_load(:car_rentals).where(user_id: current_user.id)[0]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def car_rental_owner_params
    params.require(:car_rental_owner).permit(:company_name, :company_logo)
  end
end

app/controllers/dashboard/car_rentals_controller.rb
class Dashboard::CarRentalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car_rental, only: [:update, :destroy, :edit]

  # POST /hotels
  # POST /hotels.json
  def create
    @user = User.find current_user.id
    if(!@user.car_rental_owner.nil?)
      @car_rental = CarRental.new(car_rental_params)
      @car_rental.car_rental_owner_id = @user.car_rental_owner.id

      respond_to do |format|
        if @car_rental.save
          format.html { redirect_to @car_rental, notice: 'car_rental was successfully created.' }
          format.json { render :show, status: :created, location: @car_rental }
        else
          format.html { render :new }
          format.json { render json: @car_rental.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end


  def edit
    @user = User.find current_user.id
    if(@user.car_rental_owner.nil?)
      redirect_to root_path
    end
  end


  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    @user = User.find current_user.id
    if(!@user.car_rental_owner.nil?)
      respond_to do |format|
        if @car_rental.update(car_rental_params)
          format.html { redirect_to @car_rental, notice: 'car_rental was successfully updated.' }
          format.json { render :show, status: :ok, location: @car_rental }
        else
          format.html { render :edit }
          format.json { render json: @car_rental.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    if @car_rental.vehicles.delete_all
      if @car_rental.destroy
        render :'car_rentals/success_destroy'
      else
        render :'car_rentals/fail_destroy'
      end
    else
      render :'car_rentals/fail_destroy'
    end
  end

  private
  def is_car_rental_owner?
    redirect_to root_path unless current_user.is_car_rental_owner == true
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_car_rental
    @car_rental = CarRental.eager_load(:vehicles).find(params[:id])
  end
  def car_rental_params
    params.require(:car_rental).permit(:name, :location_id, :address, :info, :number,:email , :website_url, car_rental_photos:[])
  end
end

app/controllers/dashboard/featured_hotels_controller.rb
class Dashboard::FeaturedHotelsController < ApplicationController
  before_action :set_featured_tour, only: [:destroy]


  # GET /featured_tours/new
  def new
    @featured_tour = FeaturedTour.new
    @featured_tour.hotels_id = params[:hotel_id]
  end

  # POST /featured_tours
  # POST /featured_tours.json
  def create
    @featured_tour = FeaturedTour.new(featured_tour_params)
    @featured_tour.hotels_id = params[:hotel_id]
    @featured_tour.user_id = current_user.id
    @featured_tour.featured_type = "Hotel"
    @featured_tour.payment_amount = 500 * @featured_tour.duration
    if @featured_tour.save
      redirect_to featured_create_path(@featured_tour.id), method: :post
    else
      render json: @featured_tour.errors, status: :unprocessable_entity
    end
  end

  # DELETE /featured_tours/1
  # DELETE /featured_tours/1.json
  def destroy
    @featured_tour.destroy
    respond_to do |format|
      format.html { redirect_to featured_tours_url, notice: 'Featured tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_featured_tour
    @featured_tour = FeaturedTour.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def featured_tour_params
    params.require(:featured_tour).permit(:duration)
  end
end

app/controllers/dashboard/featured_tours_controller.rb
class Dashboard::FeaturedToursController < ApplicationController
  before_action :set_featured_tour, only: [:show, :edit, :update, :destroy]

  # GET /featured_tours
  # GET /featured_tours.json
  def index
    @featured_tours = FeaturedTour.all
  end

  # GET /featured_tours/1
  # GET /featured_tours/1.json
  def show
  end

  # GET /featured_tours/new
  def new
    @featured_tour = FeaturedTour.new
    @featured_tour.tour_id = params[:tour_id]
  end

  # GET /featured_tours/1/edit
  def edit
  end

  # POST /featured_tours
  # POST /featured_tours.json
  def create
    @featured_tour = FeaturedTour.new(featured_tour_params)
    @featured_tour.tour_id = params[:tour_id]
    @featured_tour.user_id = current_user.id
    @featured_tour.featured_type = "Tour"
    @featured_tour.payment_amount = 500 * @featured_tour.duration
    if @featured_tour.save
      redirect_to featured_create_path(@featured_tour.id), method: :post
    else
      render json: @featured_tour.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /featured_tours/1
  # PATCH/PUT /featured_tours/1.json
  def update
    respond_to do |format|
      if @featured_tour.update(featured_tour_params)
        format.html { redirect_to @featured_tour, notice: 'Featured tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @featured_tour }
      else
        format.html { render :edit }
        format.json { render json: @featured_tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_tours/1
  # DELETE /featured_tours/1.json
  def destroy
    @featured_tour.destroy
    respond_to do |format|
      format.html { redirect_to featured_tours_url, notice: 'Featured tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_tour
      @featured_tour = FeaturedTour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_tour_params
      params.require(:featured_tour).permit(:duration)
    end
end

app/controllers/dashboard/hotel_managers_controller.rb
class Dashboard::HotelManagersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hotel_manager
  before_action :is_hotel_manager?


  # GET /hotel_managers
  # GET /hotel_managers.json
  def index
    @hotel = Hotel.new
    @hotels = @hotel_manager.hotels.order(created_at: :desc)
    @hotel_reviews = @hotel_manager.hotel_reviews.eager_load(:user, :hotel).order(created_at: :desc)
    @users =  HotelReview.limit(5).distinct.pluck(:user_id)
    @hotel_facilities_name = HotelFacilityName.all
  end

  # PATCH/PUT /hotel_managers/1
  # PATCH/PUT /hotel_managers/1.json
  def update
    respond_to do |format|
      if @hotel_manager.update(hotel_manager_params)
        format.html { redirect_to @hotel_manager, notice: 'Hotel manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel_manager }
      else
        format.html { render :edit }
        format.json { render json: @hotel_manager.errors, status: :unprocessable_entity }
      end
    end
  end



  private


    def is_hotel_manager?
      redirect_to root_path unless current_user.is_hotel_manager == true && current_user.id == @hotel_manager.user_id
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_manager
      @hotel_manager = HotelManager.eager_load(:hotels, :hotel_reviews).where(user_id: current_user.id)[0]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_manager_params
      params.require(:hotel_manager).permit(:company_name, :proof_of_ownership, :company_logo)
    end
end

app/controllers/dashboard/tour_details_controller.rb
class Dashboard::TourDetailsController < ApplicationController
  before_action :set_tour
  before_action :set_tour_detail, only: [:update]

  # GET /tour_details
  # GET /tour_details.json
  def index
    @trip_organizer = @tour.trip_organizer
    @tour_details = @tour.tour_details.order("day ASC")
  end

  # PATCH/PUT /tour_details/1
  # PATCH/PUT /tour_details/1.json
  def update
    @tour_detail.update(tour_detail_params)
  end

  private

    def set_tour
      @tour = Tour.eager_load(:trip_organizer, :tour_details).find(params[:tour_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_detail
      @tour_detail = @tour.tour_details.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_detail_params
      params.require(:tour_detail).permit(:day, :location, :description)
    end
end

app/helpers/trip_organizers_helper.rb
module TripOrganizersHelper
end

app/views/dashboard/trip_organizers/index.html.erb
<!-- start Container Wrapper -->
<div id="container-wrapper">
  <!-- Dashboard -->
  <div id="dashboard">

    <!-- Responsive Navigation Trigger -->
    <a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>

    <div class="dashboard-sticky-nav">
      <div class="content-left pull-left">
        <a href="<%= root_path %>"><img src="<%= image_path 'logo_bagpackers' %>" alt="logo" style="height: 50px; width: 50px"></a>
      </div>
      <div class="content-right pull-right">
        <div class="search-bar">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" id="search" placeholder="Search Now">
              <a href="#"><span class="search_btn"><i class="fa fa-search" aria-hidden="true"></i></span></a>
            </div>
          </form>
        </div>
        <div class="dropdown">
          <a href="<%= trip_organizer_path(@trip_organizer) %>">
            <div class="profile-sec">
              <div class="dash-image">
                <img src="<%= url_for @trip_organizer.company_logo  %>" alt="">
              </div>
              <div class="dash-content">
                <h4><%= @trip_organizer.company_name %></h4>
                <span>Trip Organizer</span>
              </div>
            </div>
          </a>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <div class="dropdown-item">
              <i class="sl sl-icon-envelope-open"></i>
              <span class="notify">3</span>
            </div>
          </a>
          <div class="dropdown-menu notification-menu">
            <h4> 23 Messages</h4>
            <ul>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
            <p class="all-noti"><a href="#">See all messages</a></p>
          </div>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <div class="dropdown-item">
              <i class="sl sl-icon-bell"></i>
              <span class="notify">3</span>
            </div>
          </a>
          <div class="dropdown-menu notification-menu">
            <h4> 599 Notifications</h4>
            <ul>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="notification-item">
                    <div class="notification-image">
                      <img src="<%= image_path 'comment.jpg'  %>" alt="">
                    </div>
                    <div class="notification-content">
                      <p>You have a notification.</p><span class="notification-time">2 hours ago</span>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
            <p class="all-noti"><a href="#">See all notifications</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="dashboard-nav">
      <div class="dashboard-nav-inner nav-tabs">
        <ul>
          <li class="active"><a data-toggle="tab" href="#home"><i class="sl sl-icon-settings"></i> Dashboard</a></li>
          <li><a  data-toggle="tab" href="#profile" ><i class="sl sl-icon-user"></i> Edit Profile</a></li>
          <li><a data-toggle="tab" href="#tour" ><i class="sl sl-icon-plus"></i> Add Tour</a></li>
          <li><a data-toggle="tab" href="#tours"><i class="sl sl-icon-layers"></i> Tour Listing</a></li>
          <li><a data-toggle="tab" href="#bookings"><i class="sl sl-icon-list"></i> Booking List</a></li>
          <li><a data-toggle="tab" href="#reviews"><i class="sl sl-icon-star"></i> Reviews</a></li>
          <li><%= link_to ' Logout', destroy_user_session_path, method: :delete, class: "sl sl-icon-power" %><i class=""></i></li>
        </ul>
      </div>
    </div>
    <div class="tab-content">
      <div class="dashboard-content tab-pane fade in active" id="home" >
        <div class="row">

          <!-- Item -->
          <div class="col-lg-3 col-md-6 col-xs-6">
            <div class="dashboard-stat color-1">
              <div class="dashboard-stat-content"><h4><%= @trip_organizer.tours.count  %></h4> <span>Total Tours</span></div>
              <div class="dashboard-stat-icon"><i class="im im-icon-Map2"></i></div>
            </div>
          </div>

          <!-- Item -->
          <div class="col-lg-3 col-md-6 col-xs-6">
            <div class="dashboard-stat color-2">
              <div class="dashboard-stat-content"><h4><%= @trip_organizer.bookings.count  %></h4> <span>Total Bookings</span></div>
              <div class="dashboard-stat-icon"><i class="im im-icon-Line-Chart"></i></div>
            </div>
          </div>


          <!-- Item -->
          <div class="col-lg-3 col-md-6 col-xs-6">
            <div class="dashboard-stat color-3">
              <div class="dashboard-stat-content"><h4><%= @trip_organizer.tour_reviews.count  %></h4> <span>Total Reviews</span></div>
              <div class="dashboard-stat-icon"><i class="im im-icon-Add-UserStar"></i></div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 col-xs-6">
            <div class="dashboard-stat color-4">
              <div class="dashboard-stat-content"><h4><%=  number_with_precision(@trip_organizer.tour_reviews.average(:rating), precision: 2) %></h4> <span>Rating</span></div>
              <div class="dashboard-stat-icon"><i class="im im-icon-Heart"></i></div>

            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12 col-md-12 col-xs-12 traffic">
            <div class="dashboard-list-box">
              <h4 class="gray">Recent Bookings</h4>
              <div class="table-box">
                <table class="basic-table">
                  <thead>
                  <tr>
                    <th>Date</th>
                    <th>User Name</th>
                    <th>Tour Name</th>
                    <th>No of Tickets</th>
                    <th>Payment Amount</th>
                    <th>Payment Status</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @bookings.limit(5).each do |booking| %>
                  <tr>
                    <td><%= booking.updated_at %>></td>
                    <td class="t-id"><a href="<%= user_path(booking.user) %>"> <%= booking.user.name %> </a></td>
                    <td><%= booking.tour.title %></td>
                    <td><%= booking.no_of_seats %></td>
                    <td><%= booking.payment_amount %></td>
                    <td><%= booking.payment_status %></td>
                  </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <!-- Recent Activity -->
          <div class="col-lg-7 col-md-12 col-xs-12 traffic">
            <div class="dashboard-list-box with-icons margin-top-20">
              <h4 class="gray">Recent Activities</h4>
              <ul>
                <% @tour_reviews.limit(5).each do |review| %>
                <li>
                  <i class="list-box-icon sl sl-icon-layers"></i>  <strong><a href="<%= user_path(review.user) %>"><%= review.user.name %></a></strong>  left a review with <%= review.rating %> stars on <strong><a href="<%= tour_path(review.tour) %>"> <%= review.tour.title %> </a></strong>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="col-lg-5 col-md-12 col-xs-12 traffic">
            <div class="dashboard-list-box margin-top-20 user-list">
              <h4 class="gray">User List</h4>
              <ul>
                <li>

                  <% @users.each do |user| %>
                    <% user = User.find(user) %>
                  <div class="user-list-item">
                    <div class="user-list-image">
                      <% if user.profile_picture.attached? %>
                      <img src="<%= url_for user.profile_picture  %>" alt="">
                      <% else %>
                        <img src="<%= image_path 'user_default'  %>" alt="">
                      <% end %>
                    </div>
                    <div class="user-list-content">
                      <h4> <%= user.name %> </h4>
                    </div>
                    <div class="user-btns">
                      <a href="<%= user_path(user) %>" class="button">View</a>
                    </div>
                  </div>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="row">
          <!-- site traffic -->
          <div class="col-lg-4 col-md-4 mar-b-30">
            <div class="dashboard-list-box">
              <h4 class="gray">Site Traffic</h4>
              <div id="chartContainer" style="height: 250px; width: 100%;"></div>
            </div>
          </div>

          <div class="col-lg-4 col-md-4 mar-b-30">
            <div class="dashboard-list-box">
              <h4 class="gray">Bar Chart</h4>
              <div id="barchart" style="height: 250px; width: 100%;"></div>
            </div>
          </div>

          <div class="col-lg-4 col-md-4">
            <div class="dashboard-list-box">
              <h4 class="gray">Search Engine</h4>
              <div id="piechart" style="height: 250px; width: 100%;"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="dashboard-content tab-pane fade" id="tour">
        <div class="row">
          <%= render "dashboard/tours/form", tour: @tour %>
        </div>
      </div>

      <div class="dashboard-content tab-pane fade" id="tours">
        <div class="row">
          <%= render "dashboard/tours/index", locals: @tours %>
        </div>
      </div>

      <div class="dashboard-content tab-pane fade" id="reviews">
        <div class="row">
          <%= render 'dashboard/tour_reviews/index', locals: @tour_reviews %>
        </div>
      </div>

      <div class="dashboard-content tab-pane fade" id="bookings">
        <div class="row">
          <%= render 'dashboard/bookings/index', locals: @bookings %>
        </div>
      </div>

      <div class="dashboard-content tab-pane fade" id="profile">
        <div class="row">
          <%= render "dashboard/trip_organizers/form", trip_organizer: @trip_organizer %>
        </div>
      </div>
    </div>


    <!-- Content / End -->

  </div>
  <!-- Dashboard / End -->
</div>
<!-- end Container Wrapper -->