config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :custom_trips, only: [:create, :new]

  mount Crono::Web, at: '/crono'
  get 'messages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tours, except: [:edit, :update] do
    resources :tour_details, only: [:create, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
    resources :tour_reviews, only: [:create, :destroy]
  end

  resources :blogs
  resources :locations
  get '/card/new' => 'bookings#new_card', as: :add_payment_method
  post "/card" => "bookings#create_card", as: :create_payment_method
  get '/success' => 'bookings#success', as: :success

  resources :hotels do
    resources :hotel_rooms, except: [:index]
    resources :hotel_reviews, only: [:create, :destroy]
  end
  resources :car_rentals do
    resources :vehicles
  end
  resources :car_rental_owners do
    get :my_car_rentals
  end
  resources :trip_organizers do
    get :my_tours
  end
  resources :hotel_managers do
    get :my_hotels
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end



  get 'charges/:id', to: 'charges#new', as: :new_charge
  post 'charges/:id', to: 'charges#create', as: :charges

  get 'featured_charges/:id', to: 'featured_charges#new', as: :new_featured_charge
  post 'featured_charges/:id', to: 'featured_charges#create', as: :featured_create

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :contact, only: [:index]
  resources :about, only: [:index]
  resources :posts do
    post 'delete_image_attachment/:id', to: 'posts#delete_image_attachment', as: :delete_image_attachment
  end

  resources :comments, only: [:create, :destroy]
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end
  get '/my_bookings/:id', to: 'users#my_bookings', as: :my_bookings
  resources :events, except: [:edit, :update]


    get '/feed', to:  'feed#index'

    get '/feed/front', as: "home"


  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'feed#find_friends', as: :find_friends, via: :get
  match :about, to: 'feed#about', as: :about, via: :get




  namespace :api do
    resources :tours, only: [:index, :create, :update, :destroy, :show]

    resource :users, only: [:show]
    resource :trip_organizers, only: [:create, :show, :destroy, :update, :index]
    resource :tour_details, only: [:update, :show, :destroy]
    resource :bookings, only: [:create, :destroy, :show]
      devise_for :users, as: 'api', controllers: {
          session: 'api/sessions', registrations: 'api/users/registrations'}, skip: [:password]
  end


  namespace :dashboard do
    resources :trip_organizers, only: [:index, :update]
    resources :tours, only: [:destroy, :create, :edit ,:update] do
      resources :tour_details, only: [:index, :update]
      resources :featured_tours
    end

    resources :hotel_managers, only: [:update, :index]
    resources :hotels, only: [:destroy, :create, :update, :edit] do
      resources :hotel_rooms, only: [:index, :update, :create, :new, :index]
      resources :featured_hotels, only: [:new, :create]
    end

    resources :car_rental_owners, only: [:update, :index]
    resources :car_rentals, only: [:destroy, :create, :update, :edit] do
      resources :vehicles, only: [:index, :update, :create, :new, :index]
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  rescue_from Stripe::CardError, with: :catch_exception
  def new
    @booking = Booking.find params[:id]
    if @booking.payment_status?
      redirect_to my_bookings_path(current_user.id)
    else if @booking.user_id != current_user.id
       redirect_to my_bookings_path(current_user.id)
     end
    end
  end

  def featured_new
    @featured_tour = FeaturedTour.find params[:id]
    if @featured_tour.payment_status?
      redirect_to my_bookings_path(current_user.id)
    else if @featured_tour.user_id != current_user.id
       redirect_to my_bookings_path(current_user.id)
     end
    end
  end

  def create
    StripeChargesServices.new(charges_params, current_user).call
    @booking = Booking.find params[:id]
    @booking.payment_status = true
    @booking.save

    redirect_to @booking.tour
  end


  def featured_create
    StripeChargesServices.new(charges_params, current_user).featured_call
    @featured_tour = FeaturedTour.find params[:id]
    @featured_tour.payment_status = true
    @featured_tour.save

    redirect_to @featured_tour.tour
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken, :id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<%#= form_tag charges_path(@booking.id) do %>
<!--  <article>-->
    <%# if flash[:error].present? %>
<!--      <div id="error_explanation">-->
<!--        <p><%#= flash[:error] %></p>-->
<!--      </div>-->
    <%# end %>
<!--  </article>-->
<!--<div class="container">-->
<!--  <h3 style="text-align: center"> Checkout </h3>-->
<!--  <hr>-->
<!--  <table id="cart" class="table table-hover table-condensed">-->
<!--    <thead>-->
<!--    <tr>-->
<!--      <th style="width:50%">Tour</th>-->
<!--      <th style="width:10%">Price</th>-->
<!--      <th style="width:8%">Seats</th>-->
<!--      <th style="width:22%" class="text-center">Subtotal</th>-->
<!--    </tr>-->
<!--    </thead>-->
<!--    <tbody>-->
<!--    <tr>-->
<!--      <td data-th="Product">-->
<!--        <div class="row">-->
<!--          <div class="col-sm-2 hidden-xs"><img src="http://placehold.it/100x100" alt="..." class="img-responsive"/></div>-->
<!--          <div class="col-sm-10">-->
<!--            <h4 class="nomargin"> <%#= @booking.tour.title  %> </h4>-->
<!--            <div>-->
<!--              <p>Name : <%#= @booking.user.name  %></p>-->
<!--              <p>Email : <%#= @booking.user.email  %></p>-->
<!--              <p>Phone : <%#= @booking.user.phone_number  %></p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </td>-->
<!--      <td data-th="Price"><%#= @booking.tour.price %></td>-->
<!--      <td data-th="Quantity">-->
        <%#= @booking.no_of_seats %>
<!--      </td>-->
<!--      <td data-th="Subtotal" class="text-center"><%#= @booking.payment_amount %> RS</td>-->
<!--    </tr>-->
<!--    </tbody>-->
<!--    <tfoot>-->
<!--    <tr class="visible-xs">-->
<!--      <td class="text-center"><strong>Total 1.99</strong></td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td>-->
        <%#= link_to 'Delete', tour_booking_path(@booking.tour,@booking), class:"btn btn-danger", method: :delete %>
<!--      </td>-->
<!--      <td colspan="2" class="hidden-xs"></td>-->
<!--      <td class="hidden-xs text-center"><strong><%#= @booking.payment_amount %> RS</strong></td>-->
<!--      <td>-->
<!--        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"-->
<!--                data-key="<%#= Rails.configuration.stripe[:publishable_key] %>"-->
<!--                data-description="Pay for Trip"-->
<!--                data-amount="<%#= @booking.payment_amount * 100 %>"-->
<!--                data-email="<%#= current_user.email %>"-->
<!--                data-currency="pkr"-->
<!--                data-locale="auto">-->
<!--        </script>-->
<!--      </td>-->
<!--    </tr>-->
<!--    </tfoot>-->
<!--  </table>-->
<!--</div>-->

<%# end %>
<section class="breadcrumb-outer text-center">
  <div class="container">
    <div class="breadcrumb-content">
      <h2>Booking</h2>
      <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="<%= root_path %>">Home</a></li>
          <li class="breadcrumb-item"><a href="<%= tours_path %>">Tours</a></li>
          <li class="breadcrumb-item"><a href="<%= tour_path(@booking.tour.id) %>"><%=@booking.tour.title%></a></li>
          <li class="breadcrumb-item active" aria-current="page">Booking</li>
        </ul>
      </nav>
    </div>
  </div>
  <div class="section-overlay"></div>
</section>

<div class="row shopping-cart" style="margin-top: 100px;">


  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Seats</label>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Total</label>
  </div>

  <div class="product">
    <div class="product-image">
      <%= image_tag url_for(@booking.tour.trip_images[0]), alt: 'img'%>
    </div>
    <div class="product-details">
      <div class="product-title"><%= @booking.tour.title  %></div>
      <p class="product-description">Date: <%= @booking.tour.date%> <br>  Number of Days: <%= @booking.tour.duration%></p>
    </div>
    <div class="product-price"><%= @booking.tour.price  %></div>
    <div class="product-quantity">
      <%= @booking.no_of_seats  %>
    </div>

    <div class="product-line-price" style="margin-left: 127px ;"><%= @booking.payment_amount %></div>
  </div>


  <div class="totals">

<!--    <div class="totals-item">-->
<!--      <label>Tax (5%)</label>-->
<!--      <div class="totals-value" id="cart-tax">3.60</div>-->
<!--    </div>-->
<!--    <div class="totals-item">-->
<!--      <label>Shipping</label>-->
<!--      <div class="totals-value" id="cart-shipping">15.00</div>-->
<!--    </div>-->
    <div class="totals-item totals-item-total">
      <label>Grand Total</label>
      <div class="totals-value" id="cart-total"><%= @booking.payment_amount %></div>
    </div>
  </div>

<!--  <button class="checkout" style="margin-bottom: 20px">Checkout</button>-->
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Checkout"
          data-amount="<%= @booking.payment_amount * 100 %>"
          data-email="<%= current_user.email %>"
          data-currency="pkr"
          data-locale="auto">
      document.getElementsByClassName("stripe_checkout_app").style.float='right';
  </script>



</div>